packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@cloudflare/workers-types": ^4.20260317.1
  "@tailwindcss/vite": ^4.2.2
  "@tanstack/react-query": ^5.95.0
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@testing-library/user-event": ^14.6.1
  "@types/node": ^24
  date-fns: ^4.1.0
  jsdom: ^29.0.1
  recharts: ^3.8.0
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.13
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wrangler: ^4.76.0

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
